version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: local-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: graphql-todo-backend
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://root:password@mongo:27017/
    depends_on:
      - mongo
  frontend:
      build: ./frontend
      container_name: vite-frontend
      restart: unless-stopped
      ports:
        - "5173:80"
      depends_on:
        - backend
volumes:
  mongo-data:
